// Generated by gencpp from file ros_learning/Num.msg
// DO NOT EDIT!


#ifndef ROS_LEARNING_MESSAGE_NUM_H
#define ROS_LEARNING_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_learning
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num(0)
    , fsr1(0)
    , fsr2(0)
    , fsr_raw()  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num(0)
    , fsr1(0)
    , fsr2(0)
    , fsr_raw(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef int32_t _fsr1_type;
  _fsr1_type fsr1;

   typedef int32_t _fsr2_type;
  _fsr2_type fsr2;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _fsr_raw_type;
  _fsr_raw_type fsr_raw;





  typedef boost::shared_ptr< ::ros_learning::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_learning::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::ros_learning::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::ros_learning::Num > NumPtr;
typedef boost::shared_ptr< ::ros_learning::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_learning::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_learning::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_learning::Num_<ContainerAllocator1> & lhs, const ::ros_learning::Num_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.fsr1 == rhs.fsr1 &&
    lhs.fsr2 == rhs.fsr2 &&
    lhs.fsr_raw == rhs.fsr_raw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_learning::Num_<ContainerAllocator1> & lhs, const ::ros_learning::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_learning::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_learning::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_learning::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_learning::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_learning::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_learning::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_learning::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dbc71f4adf6d91823c26a117a2b6ba4";
  }

  static const char* value(const ::ros_learning::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dbc71f4adf6d918ULL;
  static const uint64_t static_value2 = 0x23c26a117a2b6ba4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_learning::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_learning/Num";
  }

  static const char* value(const ::ros_learning::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_learning::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n"
"int32 fsr1\n"
"int32 fsr2\n"
"int32[] fsr_raw\n"
;
  }

  static const char* value(const ::ros_learning::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_learning::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.fsr1);
      stream.next(m.fsr2);
      stream.next(m.fsr_raw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_learning::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_learning::Num_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "fsr1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fsr1);
    s << indent << "fsr2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fsr2);
    s << indent << "fsr_raw[]" << std::endl;
    for (size_t i = 0; i < v.fsr_raw.size(); ++i)
    {
      s << indent << "  fsr_raw[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.fsr_raw[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_LEARNING_MESSAGE_NUM_H
