// Generated by gencpp from file ros_learning/servoRequest.msg
// DO NOT EDIT!


#ifndef ROS_LEARNING_MESSAGE_SERVOREQUEST_H
#define ROS_LEARNING_MESSAGE_SERVOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_learning
{
template <class ContainerAllocator>
struct servoRequest_
{
  typedef servoRequest_<ContainerAllocator> Type;

  servoRequest_()
    : a(0)  {
    }
  servoRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::ros_learning::servoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_learning::servoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct servoRequest_

typedef ::ros_learning::servoRequest_<std::allocator<void> > servoRequest;

typedef boost::shared_ptr< ::ros_learning::servoRequest > servoRequestPtr;
typedef boost::shared_ptr< ::ros_learning::servoRequest const> servoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_learning::servoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_learning::servoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_learning::servoRequest_<ContainerAllocator1> & lhs, const ::ros_learning::servoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_learning::servoRequest_<ContainerAllocator1> & lhs, const ::ros_learning::servoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_learning::servoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_learning::servoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_learning::servoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_learning::servoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_learning::servoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_learning::servoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_learning::servoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::ros_learning::servoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_learning::servoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_learning/servoRequest";
  }

  static const char* value(const ::ros_learning::servoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_learning::servoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"\n"
;
  }

  static const char* value(const ::ros_learning::servoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_learning::servoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_learning::servoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_learning::servoRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_LEARNING_MESSAGE_SERVOREQUEST_H
